### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by gwillem** [ByteInternet/hypernode-vagrant#12]
Could/should we integrate with Docker?

Pro
- Docker boots faster: 10s as opposed to Virtualbox 1m30s
- Docker uses less disk space with multiple containers because it only writes deltas
- Docker has higher buzz factor

Con
- Docker env will deviate more from prod env because of its architecture. 

Perhaps basic LXC is better because it is fast _and_ similar to prod. But am not sure if there are easy options to run LXC on MacOSX. For Docker there is boot2docker which seems quite solid already.

**Comment by mhobbink** [comment]
Any progress on this? Looking forward for a docker integration

**Comment by allardhoeve** [comment]
I'm afraid this won't happen. Docker requires each service to be run in its
own container with a controlling tty. That is diametrically opposed to
Vagrant where an OS runs in its entirety. (Most importantly: init)

As Hypernode is not designed from the ground up as a collection of
containerized services, we would have to redesign the platform to run it
with docker compose and data volumes.

As an alternative, we are planning to release an LXC box that would bring
the speed of Docker. (Docker is based on LXC).

**Comment by vdloo** [comment]
We just released an experimental LXC version. See https://github.com/ByteInternet/hypernode-vagrant/pull/51. Take a look at [this part of the README](https://github.com/ByteInternet/hypernode-vagrant#starting-the-test-environment) for how to enable it.
