### ISSUE TITLE
LXC support for virbr0 bridge 

### ISSUE THREAD

**Issue by Desmaster** [ByteInternet/hypernode-vagrant#120]
When I open `~/.vagrant.d/boxes/hypernode_php7/3455/lxc/lxc.conf`, I see the following line: 

`lxc.network.link=lxcbr0`

Where does this line come from? From the Hypernode image or am I missing some configuration myself? In my lxc configuration I have set the `lxc.network.link` to `virbr0`, but when using `vagrant up`, it still crashes because it wants to attach the container to `lxcbr0`.

Fedora uses a certain bridge `virbr0`, but the Hypernode seems to default on bridge `lxcbr0`.

**Comment by tomlankhorst** [comment]
Looks to me that it comes from /etc/lxc/default.conf.



Op di 13 dec. 2016 om 22:09 schreef Timon de Groot <notifications@github.com

**Comment by Desmaster** [comment]
That's what I was thinking. As I already mentioned, I have set the network link in `/etc/lxc/default.conf` to `virbr0`. 

After some more digging it seems the issue seems to be that the lxc.network.link also gets set to `lxcbr0` in `/var/lib/lxc/hypernode_hypernode_1481662665626_50219/config`. 

Any thoughts on this?

**Comment by vdloo** [comment]
Yeah I think that lxc.conf is baked into the image. Maybe you can try setting it in the Vagrantfile with something like `lxc__bridge_name`. https://github.com/fgrehm/vagrant-lxc#private-networks-experimental

**Comment by Desmaster** [comment]
@vdloo thanks! You've sent me into the right direction, I ended up adding the following line:

![image](https://cloud.githubusercontent.com/assets/1165302/21239981/8f6488f6-c309-11e6-8b48-422a09fcc82e.png)

I guess it's fixed for now, it's an easy fix this way. Would it be an idea to add this line to the Vagrantfile and default it to `lxcbr0`? That way the bridge name used in the Vagrantfile is always used by the lxc container.

**Comment by vdloo** [comment]
We can't add it unconditionally since it is not `virbr0` on all distros. For example, `lxcbr0` is the default bridge interface for lxc containers on Debian derivatives. That is the reason why it was in the image lxc.conf (because we build on Debian). However what we could do is detect whether the system is a Redhat derivative (CentOS, Fedora) and then set it to `virbr0`.
