### ISSUE TITLE
Folder names with a dash (-) are not working correctly

### ISSUE THREAD

**Issue by dverkade** [ByteInternet/hypernode-vagrant#129]
Folder names with a dash (-) are not working correctly.

I have fixed this in this commit of our fork: 
https://bitbucket.org/creaminternet/hypernode/commits/07e3feddd2fe20d2f964c012ad5d861d81997e70

**Comment by genisd** [comment]
Can you open a PR for this?
Thank you! :-)

**Comment by vdloo** [comment]
hi @dverkade I started back-porting your changes [here](https://github.com/ByteInternet/hypernode-vagrant/pull/128), maybe you can add the dash-fix as a pr on that pr. Note that I did not include the dot in the default_domain like you guys did:

```
directory_alias = hypernode_host + "." + settings['hostmanager']['default_domain']
```

I think 'default_domain' describes 'somedomain.io' better than '.somedomain.io'

**Comment by dverkade** [comment]
Hi @vdloo 

I see you have backported this feature and it's now in the Hypernode vagrant. I will close this issue.
