### ISSUE TITLE
Installing the vagrant gives errors

### ISSUE THREAD

**Issue by janw-oostendorp** [ByteInternet/hypernode-vagrant#14]
After running `vagrant up` it gives errors about fetching archives.  
Is there a way around this or are some of the byte archives broken?
See screenshots.
![2015-03-09_220048](https://cloud.githubusercontent.com/assets/1026882/6564423/ae373a12-c6a8-11e4-958b-260c92929a78.jpg)
![2015-03-09_220420](https://cloud.githubusercontent.com/assets/1026882/6564422/ae36977e-c6a8-11e4-9e17-b4e6cf028451.jpg)

**Comment by allardhoeve** [comment]
I think the networking is not working correctly. Your host machine does not
seem to forward any connections.

Although, why it would try to connect to port 22275, I don't know.

Did you set any proxies?

**Comment by janw-oostendorp** [comment]
I don't use any proxies (as far as I know). Pinging does not respond to the IP. The URL's do work.
[This](http://ping.eu/ping/) also gives 0 result for the IP.

I'm not 100% sure but at the office I got the same errors.

**Comment by gwillem** [comment]
Hi Jan, thanks for reporting & you are absolutely right.

Quick fix:
```
rm /etc/apt/apt.conf.d/02proxy
```

We will roll out a new release soon.

**Comment by allardhoeve** [comment]
Hey @janw-oostendorp, I've updated the Hypernode Vagrant image to the latest build. It does not have any proxy definitions.

Can you run `vagrant box update` and then retry?

**Comment by janw-oostendorp** [comment]
Yes it works!
Thanks!
