### ISSUE TITLE
hypernode.local doesn't work 127.0.0.1:8080 does

### ISSUE THREAD

**Issue by AngelsDustz** [ByteInternet/hypernode-vagrant#153]
My issues is exactly the same as #150 except the pull didn't fix it for me.

OS; Linux arch 4.11.5-1-ARCH #1 SMP PREEMPT Wed Jun 14 16:19:27 CEST 2017 x86_64 GNU/Linux
Vagrant ifconfig:
```
enp0s3    Link encap:Ethernet  HWaddr 08:00:27:c3:0a:85  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2669 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2046 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:288105 (288.1 KB)  TX bytes:363316 (363.3 KB)

enp0s8    Link encap:Ethernet  HWaddr 08:00:27:16:5c:9f  
          inet addr:172.28.128.3  Bcast:172.28.128.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3070 (3.0 KB)  TX bytes:2172 (2.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:125 errors:0 dropped:0 overruns:0 frame:0
          TX packets:125 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:27045 (27.0 KB)  TX bytes:27045 (27.0 KB)
```

**Comment by vdloo** [comment]
Hi @AngelsDustz, does the enp0s8 ip work? In the example you listed that would be `172.28.128.3:80`, or just `172.28.128.3`. What does your `/etc/hosts` look like on the host?

**Comment by AngelsDustz** [comment]
172.28.128.3 does not work my hosts file looks like:
```
#
# /etc/hosts: static lookup table for host names
#

#<ip-address>	<hostname.domain.org>	<hostname>
127.0.0.1	localhost.localdomain	localhost
::1		localhost.localdomain	localhost
127.0.1.1	arch.localdomain	arch

# End of file

## vagrant-hostmanager-start id: 65315aa0-408e-4c08-b067-00775a390897
172.28.128.3	7accd3-nano-magweb-vgr.nodes.hypernode.local
172.28.128.3	hypernode.local
172.28.128.3	hypernode-alias
172.28.128.3	nano.hypernode.local
172.28.128.3	7accd3.hypernode.local
172.28.128.3	my-custom-store-url1.local
172.28.128.3	my-custom-store-url2.local
## vagrant-hostmanager-end
```

**Comment by vdloo** [comment]
Hi @AngelsDustz, if 172.28.128.3 does not work then there's likely an issue with your firewall. Maybe there's some clues in `iptables -L`. It could also be VirtualBox, what version are you running? Have you configured anything special?

**Comment by AngelsDustz** [comment]
The vagrant box returns:
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

The host machine returns:
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

Virtualbox is version : 5.1.22 r115126

All configs etc. is stock.
However I did notice this:
```
==> hypernode: Waiting for machine to boot. This may take a few minutes...
    hypernode: SSH address: 127.0.0.1:2222
    hypernode: SSH username: vagrant
    hypernode: SSH auth method: private key
    hypernode: Warning: Connection reset. Retrying...
    hypernode: Warning: Remote connection disconnect. Retrying...
```

Not sure if it is related.

**Comment by vdloo** [comment]
Hi @AngelsDustz, there were some issues previously reported on Archlinux and derivatives with this box for Vagrant version 5.1.20 and up. Check out [this issue](https://github.com/ByteInternet/hypernode-vagrant/issues/149). If you still have an older VirtualBox tar in your pacman archive you can try that.

**Comment by AngelsDustz** [comment]
Hi there, just tried downgrading to 5.1.18-2, no success either same issue.
I just saw there was a hypernode update so I am going to revert back to 5.1.22 and test the new update.

**Comment by vdloo** [comment]
I'm afraid that won't fix your issue, we changed nothing relating to this. Our continuous integration builds new boxes for every build so the update was an automated build. Can you try the precise version of the box? You can edit `local.xml` and change `ubuntu_version: xenial` to `ubuntu_version: precise` and re-create the box. If that also doesn't work it is likely an issue with your environment.

**Comment by AngelsDustz** [comment]
Even tried that no result, I have kept all configs stock.
Where would I start to look to find the issue?

**Comment by vdloo** [comment]
Do you have any other Vagrant boxes on that machine that do work? You can check the differences in configuration between this one and another one that does work on your machine. Maybe you can then pinpoint the specific configuration that does not work. This box uses private networking for the default, see [this part of the vagrantfile](https://github.com/ByteInternet/hypernode-vagrant/blob/master/Vagrantfile#L78). You can read more about the virtualbox private networking setting in vagrant [here](https://www.vagrantup.com/docs/virtualbox/networking.html). 

Have you tried the 'lxc' version of this box? You could try that, but like I wrote [here](https://github.com/ByteInternet/hypernode-vagrant/issues/149), setting up proper LXC bridging on Arch is tricky though so watch out you don't lock yourself out of your box by messing up the networking if it is a remote machine you are working on.

**Comment by vdloo** [comment]
Also, note that Vagrant calls it 'private networking' but the VirtualBox terminology is 'host-only networking' afaik. Maybe this segment of the VirtualBox Archlinux wiki will be of help: https://wiki.archlinux.org/index.php/VirtualBox#Load_the_VirtualBox_kernel_modules

**Comment by AngelsDustz** [comment]
Still an existing issue not really sure where to look, I could try the LXC but other than that you'd think it would work since everything is configured properly.

**Comment by vdloo** [comment]
If you have an Ubuntu or macosx machine available I suggest you try it on that. We officially develop this box for Ubuntu and Macosx only, however it should work on any other distro with the right configurations. But as it doesn't seem to work out of the box for you in Arch it's probably an uphill battle getting it to run and you'd have to figure out some stuff yourself. You can do that and it has worked on Arch in the past for other people and myself, but if you do not want to tinker the easiest option is to just run it on a more out of the box compatible distro.

**Comment by AngelsDustz** [comment]
Wew alrighty it's fixed. The potential cause was lacking `net-tools` package. so PEBKAC I guess, sorry for the bothering!

**Comment by vdloo** [comment]
Good to hear that you figured it out. I've added [a section to the README](https://github.com/ByteInternet/hypernode-vagrant/pull/156) so people in the future might save some time debugging if they run in to this as well. Thanks for the feedback
