### ISSUE TITLE
Mailhog not working on xenial

### ISSUE THREAD

**Issue by Melleschepers** [ByteInternet/hypernode-vagrant#159]
Mailhog is not working on a fresh Vagrant box with **Xenial**
(ps -A | grep mail ...... shows nothing)

On a fresh Vagrant box precise there is no problem, and mailhox is working.
(ps -A | grep mail ...... shows: 1514 ?        00:00:00 mailhog) #d

**Comment by vdloo** [comment]
Hi, it looks like we haven't ported the upstart init script for that service to systemd yet. I'll create a PR internally to change that and we'll push a new box with that fixed soon. For now you can do this to get it running in the current release manually:

```bash
cat <<'EOF' > /etc/systemd/system/multi-user.target.wants/mailhog.service
[Unit]
Description=MailHog Service
After=network.target

[Service]
Environment="HOME=/home/mailhog"
User=mailhog
Group=mailhog
Type=simple
ExecStart=/usr/bin/mailhog
Restart=always
OOMScoreAdjust=-1000

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

systemctl start mailhog
```

You should then have it up and running, you can check with `systemctl status`
```bash
root@beb7b8-projects-magweb-vgr /etc/systemd/system/multi-user.target.wants # systemctl status mailhog
● mailhog.service - MailHog Service
   Loaded: loaded (/etc/systemd/system/multi-user.target.wants/mailhog.service; bad; vendor preset: enabled)
   Active: active (running) since Wed 2017-07-05 13:25:35 UTC; 2min 28s ago
 Main PID: 4018 (mailhog)
   CGroup: /system.slice/mailhog.service
           └─4018 /usr/bin/mailhog
```

**Comment by Melleschepers** [comment]
Thanks! Working fine now with the manual fix 👍
