### ISSUE TITLE
Vagrant box stops working with Magento 2 development

### ISSUE THREAD

**Issue by dverkade** [ByteInternet/hypernode-vagrant#164]
**Steps to reproduce:**

- Use the Hypernode Vagrant for Magento 2 for an extended period of time for development.

**Result:**

We start getting file not found errors. 
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/40194/2540006/okZRAoxp2EgwGBm/upload.png
We are not getting these errors 

**Expected result:**

Vagrant box keeps working and keeps returning the same result no matter how long the box has been running or you are developing on it. 

**Workaround to fix issue:**

Execute the command vagrant reload in order to restart the virtualbox

**Comment by vdloo** [comment]
Hi @dverkade, that's strange. We don't run these boxes for longer than an hour internally so we never noticed this bug. My guess is that it's a systemd timer auto-updating some stuff in the background and breaks the Nginx config somehow (maybe there's some stuff left in the VirtualBox base image that we didn't clear out).

I see that in the Virtualbox box version 4219 these timers are listed:
```
root@beb7b8-projects-magweb-vgr /home/vagrant # systemctl list-timers --all
NEXT                         LEFT       LAST                         PASSED       UNIT                         ACTIVATES
Thu 2017-07-13 09:58:55 UTC  11min left n/a                          n/a          systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Thu 2017-07-13 23:28:17 UTC  13h left   Thu 2017-07-13 09:44:00 UTC  3min 54s ago apt-daily.timer              apt-daily.service
n/a                          n/a        n/a                          n/a          ureadahead-stop.timer        ureadahead-stop.service

3 timers listed.
```

Can you try disabling the apt-daily.timer and see if that helps?
```
# systemctl disable apt-daily.timer
```

Also can you try booting a new box and running `apt-get update; apt-get upgrade` and see if that leaves it in the `file not found` state? 

And if you have a box running in this state, can you look up some more info? What does `pdstatus` say? That tests the webstack services:
```
# pdstatus
everything ok
```
Maybe there are some clues in the /var/log/nginx/error.log?

**Comment by vdloo** [comment]
Also is it specific for Magento 2 or did you only test with Magento 2?

**Comment by dverkade** [comment]
This is no longer an issue, so will close this issue.
