### ISSUE TITLE
Integrate with nfs guest

### ISSUE THREAD

**Issue by gwillem** [ByteInternet/hypernode-vagrant#17]
Reported by @IvanChepurnyi
https://github.com/Learnosity/vagrant-nfs_guest

**Comment by vdloo** [comment]
nfs_guest is supported now https://github.com/ByteInternet/hypernode-vagrant/pull/85, install the plugin ```vagrant plugin install vagrant-nfs_guest`` and choose it as the fs type in the 'vagrant up' dialogue or change the fs type to 'nfs_guest' in the local.yml.
