### ISSUE TITLE
Rewrite issues nginx?

### ISSUE THREAD

**Issue by reinos** [ByteInternet/hypernode-vagrant#170]
After installing Magento 2 and building the static files i miss the styles for the site.

![image](https://user-images.githubusercontent.com/633730/28780214-3cb2704a-7606-11e7-8f2e-3dc9f7c9793b.png)

Removing the /versioxxxx/ shows me the file, so the files are there in the right place.

After checking the .htaccess that comes with magento 2 in the folder pub/static/ i see the rewrite 

```
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Remove signature of the static files that is used to overcome the browser cache
    RewriteRule ^version.+?/(.+)$ $1 [L]

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-l

    RewriteRule .* ../static.php?resource=$0 [L]
</IfModule>
```

thinking about it, i run on `nginx` so the htaccess is not working. Or do i miss someting?

**Comment by vdloo** [comment]
Hi @reinos, I think support@byte would be a better place for these not hypernode-vagrant specific issues. This issue tracker is really for problems with the Vagrant box and the tooling around it. Nginx does not use .htaccess files, that's an Apache thing. We don't run Apache on Hypernodes. See this article: https://support.hypernode.com/knowledgebase/how-to-use-nginx/#Converting_htaccess_files_to_Nginx_configuration

**Comment by reinos** [comment]
ok, thanks.
