### ISSUE TITLE
Upgrade virtualbox to PHP7.1

### ISSUE THREAD

**Issue by paales** [ByteInternet/hypernode-vagrant#175]
It seems that the lxc box has 7.1 builds available for a pretty long time, but the virtual box doesn't. 
http://vagrant.hypernode.com/customer/php7/catalog.json

Could you guys upgrade to the latest version pretty please?

**Comment by paales** [comment]
Oh, apparently I can't read. It states `hypernode_php7.lxc.release-4217.box` I misread the L for a 1... Well the feature request still stands :)

**Comment by vdloo** [comment]
Hi @paales, we don't have PHP 7.1 or [MySQL 5.7](https://github.com/ByteInternet/hypernode-vagrant/issues/176) on our immediate roadmap for Hypernode yet. If you want you can create a suggestion [on our uservoice](https://hypernode.uservoice.com/forums/242854-hypernode), if issues get enough votes that might influence our priorities.

**Comment by paales** [comment]
@vdloo I don't think decisions should be made by user voice, but by metrics about the usage. PHP 7.1 allows us to use modern libraries that support PHP7.1 only, it is the future.

Since PHP7.2 is out already, it seems a lit lagging to not support 7.1, but that is probably my naive developer opinion ;)

**Comment by pauluse** [comment]
PHP 7.1 was added in 2347775. If you modify your PHP version in your `local.yml` and issue a `vagrant provision` you should be running on PHP 7.1

```
vagrant@c5686e-hypernode-magweb-vgr:~$ php -v
PHP 7.1.13-1 (cli) (built: Feb  2 2018 13:35:18) ( NTS )
```

**Comment by paales** [comment]
Cool cool cool!

**Comment by vdloo** [comment]
Hi, note that we are still revising our module packaging and that not all required modules for Magento are included in the box yet. For example, php-igbinary, php-redis and php-redis among others are still missing.
