### ISSUE TITLE
Provision error with LXC on Ubuntu 16.04

### ISSUE THREAD

**Issue by pauluse** [ByteInternet/hypernode-vagrant#179]
After checking out the repository and running "vagrant up --provicer=lxc" twice (first to create the local.yml) vagrant throws the following error:

```
==> hypernode: Importing base box 'hypernode_xenial'...
==> hypernode: Checking if box 'hypernode_xenial' is up to date...
==> hypernode: Pruning invalid NFS exports. Administrator privileges will be required...
==> hypernode: Setting up mount entries for shared folders...
    hypernode: /vagrant => /home/paul/vagrant/magento2
==> hypernode: Starting container...
==> hypernode: Waiting for machine to boot. This may take a few minutes...
    hypernode: SSH address: 10.0.3.133:22
    hypernode: SSH username: vagrant
    hypernode: SSH auth method: private key
    hypernode:
    hypernode: Vagrant insecure key detected. Vagrant will automatically replace
    hypernode: this with a newly generated keypair for better security.
    hypernode:
    hypernode: Inserting generated public key within guest...
    hypernode: Removing insecure key from the guest if it's present...
    hypernode: Key inserted! Disconnecting and reconnecting using new SSH key...
==> hypernode: Machine booted and ready!
==> hypernode: Setting hostname...
==> hypernode: Exporting NFS shared folders...
==> hypernode: Preparing to edit /etc/exports. Administrator privileges will be required...
==> hypernode: Mounting NFS shared folders...
==> hypernode: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
==> hypernode: [vagrant-hostmanager:host] Updating hosts file on your workstation (password may be required)...
==> hypernode: Running provisioner: shell...
    hypernode: Running: /tmp/vagrant-shell20180129-2460-16tqn.sh
==> hypernode: Running provisioner: shell...
    hypernode: Running: /tmp/vagrant-shell20180129-2460-17761xa.sh
    hypernode: Synchronizing state of php5.5-fpm.service with SysV init with /lib/systemd/systemd-sysv-install...
    hypernode: Executing /lib/systemd/systemd-sysv-install disable php5.5-fpm
    hypernode: insserv: warning: current start runlevel(s) (empty) of script `php5.5-fpm' overrides LSB defaults (2 3 4 5).
    hypernode: insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `php5.5-fpm' overrides LSB defaults (0 1 6).
    hypernode: Synchronizing state of php5.6-fpm.service with SysV init with /lib/systemd/systemd-sysv-install...
    hypernode: Executing /lib/systemd/systemd-sysv-install disable php5.6-fpm
    hypernode: insserv: warning: current start runlevel(s) (empty) of script `php5.6-fpm' overrides LSB defaults (2 3 4 5).
    hypernode: insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `php5.6-fpm' overrides LSB defaults (0 1 6).
    hypernode: insserv: warning: current start runlevel(s) (empty) of script `php5.6-fpm' overrides LSB defaults (2 3 4 5).
    hypernode: insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `php5.6-fpm' overrides LSB defaults (0 1 6).
    hypernode: update-alternatives: using /usr/bin/php7.0 to provide /usr/bin/php (php) in manual mode
    hypernode: Synchronizing state of php7.0-fpm.service with SysV init with /lib/systemd/systemd-sysv-install...
    hypernode: Executing /lib/systemd/systemd-sysv-install enable php7.0-fpm
    hypernode: insserv: warning: current start runlevel(s) (empty) of script `php7.0-fpm' overrides LSB defaults (2 3 4 5).
    hypernode: insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `php7.0-fpm' overrides LSB defaults (0 1 6).
    hypernode: Cannot open /var/lib/varnish/7ae733-magento2-magweb-vgr/_.vsm: No such file or directory
    hypernode: Cannot open /var/lib/varnish/7ae733-magento2-magweb-vgr/_.vsm: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

My local.yml looks like this and I'm running on box version 4832 (newest as of this moment).
```
---
fs:
  folders:
    magento2:
      host: "/home/paul/projects/magento2"
      guest: "/data/web/projects"
    nginx:
      host: data/web/nginx/
      guest: "/data/web/nginx/"
  type: nfs
  disabled_folders:
    magento1:
      host: data/web/public
      guest: "/data/web/public"
hostmanager:
  default_domain: magento2.local
magento:
  version: 2
php:
  version: 7.0
varnish:
  state: false
firewall:
  state: false
cgroup:
  state: false
xdebug:
  state: false
vagrant:
  box: hypernode_xenial
  box_url: http://vagrant.hypernode.com/customer/xenial/catalog.json
ubuntu_version: xenial
```

**Comment by vdloo** [comment]
Hi @pauluse, take a look at this similar issue: https://github.com/ByteInternet/hypernode-vagrant/issues/167 There might be some suggestions that could help you fix the problem

**Comment by pauluse** [comment]
@vdloo changing `PrivateDevices=yes` to `PrivateDevices=no` seems to fix the problem. But is there any way to make this work from the beginning?

Also, when trying to either halt or destroy my vagrant I get the follow error:
```
DEBUG remove_tmp_files: Removing temporary files
 INFO subprocess: Starting process: ["/usr/bin/sudo", "/usr/bin/env", "lxc-attach", "--name", "magento2_hypernode_1517241590654_42117", "--", "findmnt -R /tmp -o TARGET --list --noheadings | xargs -L 1 --no-run-if-empty umount"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: lxc-attach: attach.c: lxc_attach_run_command: 1292 No such file or directory - Failed to exec "findmnt -R /tmp -o TARGET --list --noheadings | xargs -L 1 --no-run-if-empty umount".
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 255
ERROR warden: Error occurred: There was an error executing ["sudo", "/usr/bin/env", "lxc-attach", "--name", "magento2_hypernode_1517241590654_42117", "--", "findmnt -R /tmp -o TARGET --list --noheadings | xargs -L 1 --no-run-if-empty umount"]
```

Another strange issue I have is where I cant switch to the app user (both in LXC and virtualbox). Whilest this works on a Windows host machine this doesn't seem to work on a Ubuntu host system.
Windows (Release 4832):
```
vagrant@deba19-magento2-magweb-vgr:~$ pwd && id
/home/vagrant
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lxd),115(lpadmin),116(sambashare)
vagrant@deba19-magento2-magweb-vgr:~$ sudo su - app
app@deba19-magento2-magweb-vgr:~$ pwd && id
/data/web
uid=197609(app) gid=197121(app) groups=197121(app),4(adm),122(varnish),998(mysql)
```

Ubuntu (Release 4832):
```
vagrant@7ae733-magento2-magweb-vgr:~$ pwd && id
/home/vagrant
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lxd),115(lpadmin),116(sambashare)
vagrant@7ae733-magento2-magweb-vgr:~$ sudo su - app
vagrant@7ae733-magento2-magweb-vgr:~$ pwd && id
/data/web
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),4(adm),122(varnish),998(mysql)
```

I'm not sure whether this has to do with my host machine or the guest system. The host system runs on `Ubuntu 16.04 LTS` with `4.13.0-32-generic`

**Comment by vdloo** [comment]
>  But is there any way to make this work from the beginning?

We need to change this in our base image. I'll add an issue to our internal jira so we can take a look at implementing that.

**Comment by pauluse** [comment]
Alright, for now I'll try to survive with changing the file then :-)
Do you have any idea regarding the user switching issue? This issue doesn't occur on a Windows or Mac host machine but happens on Ubuntu. :/

**Comment by vdloo** [comment]
I've tested on Ubuntu 16.04.3 LTS with a 4.4.0-112-generic kernel with lxc (box version v4832) and it works here:
```
vagrant@beb7b8-projects-magweb-vgr:~$ sudo su - app
app@beb7b8-projects-magweb-vgr:~$ 
```
but you mentioned that the same issue exists in virtualbox? Then I do not know what might be causing it.  Note that the SSH public keys are copied from your agent on the host to the box [here](https://github.com/ByteInternet/hypernode-vagrant/blob/master/vagrant/provisioning/hypernode.sh#L39). You should be able to log in to the vagrant box directly as either app or root.
```
vdloo@workstation4:~/code/projects/hypernode-vagrant$ vagrant ssh-config
Host hypernode
  HostName 10.0.3.133
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/vdloo/code/projects/hypernode-vagrant/.vagrant/machines/hypernode/lxc/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes

vdloo@workstation4:~/code/projects/hypernode-vagrant$ ssh app@10.0.3.133 whoami
app
vdloo@workstation4:~/code/projects/hypernode-vagrant$ ssh root@10.0.3.133 whoami
root
```

**Comment by pauluse** [comment]
@vdloo which version of Vagrant are you using? I'm currently running version `2.0.2`.
I just did a clean install of `Ubuntu 16.04 LTS`, installed vagrant, installed `lxc` and `lxc-templates` through `apt` and did a checkout of the hypernode-vagrant repository. Same issues as mentioned above are present.

The only thing I could think of now is a possible version difference between our vagrant versions which are causing the trouble.

**Comment by vdloo** [comment]
This is what I am running:
```
$ vagrant --version
Vagrant 2.0.0
$ VirtualBox --help
Oracle VM VirtualBox Manager 5.0.26
$ apt-cache policy lxc
lxc:
  Installed: 2.0.8-0ubuntu1~16.04.2
  Candidate: 2.0.8-0ubuntu1~16.04.2
  Version table:
 *** 2.0.8-0ubuntu1~16.04.2 500
        500 http://nl.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://nl.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages
        100 /var/lib/dpkg/status
```

Was your ssh agent running when you ran vagrant up? "eval \`ssh-agent -s\`; ssh-add"

**Comment by pauluse** [comment]
My ssh agent was not running since I was connecting from a Windows machine to the Ubuntu host system. But even when I run the commands from the host system (with ssh-agent enabled and available identities) the problem still presists.

From the host machine (with ssh-agent enabled) I can indeed connect through app@10.0.3.133 but as soon as I'm logged in I'm in the guest system as the user vagrant.

I just can't see whats different between our systems (besides me not running VirtualBox). I'll try with Vagrant 2.0.0 but maybe I should just give up on this and look for some docker solution to run a similar Hypernode environment.

**Comment by vdloo** [comment]
> but as soon as I'm logged in I'm in the guest system as the user vagrant

This is very strange behavior indeed. I do not know what might be causing it, if you do find out please let us know.

**Comment by pauluse** [comment]
@vdloo I assume you use `nfs` for the FS type as well, right?

**Comment by vdloo** [comment]
No, currently my `local.xml` is set to use `type: rsync`:
```
fs:
  folders:
    magento2:
      host: data/web/magento2
      guest: "/data/web/magento2"
    nginx:
      host: data/web/nginx/
      guest: "/data/web/nginx/"
  type: rsync
  disabled_folders:
    magento1:
      host: data/web/public
      guest: "/data/web/public"
```

If you are going to use nfs I would recommend to use [nfs_guest](https://github.com/ByteInternet/hypernode-vagrant/issues/17) instead, that is more performance because most of the heavy IO will happen inside the box. With nfs_guest the host will mount the filesystem of the guest, making all IO local in the guest which will benefit performance in Magento a lot.

**Comment by vdloo** [comment]
If it also happens in virtualbox then it is probably not a kernel issue. My vagrant plugin list looks like:
```
$ vagrant plugin list
vagrant-hostmanager (1.8.7)
vagrant-hypconfigmgmt (0.0.9)
  - Version Constraint: 0.0.9
vagrant-lxc (1.2.3)
vagrant-share (1.1.9, system)
vagrant-vbguest (0.15.0)
```

**Comment by pauluse** [comment]
I'm giving up on the LXC box, I have no idea what the heck is going on (especially since I'm on a clean installation of everything and tried the versions equal to yours). I'll close this issue for now, thanks for the effort.

**Comment by vdloo** [comment]
Hi @pauluse,

The `Cannot open /var/lib/varnish/7ae733-magento2-magweb-vgr/_.vsm: No such file or directory` should be fixed in v4835. If you update your box with `vagrant box update` you shouldn't need to work around the failing varnish anymore.

**Comment by pauluse** [comment]
Hey @vdloo 

This one is fixed indeed, thanks (v4844). I can even change to the app user now, so thats good news. Maybe something was broken in the v4832 box, I have no clue.

**Comment by vdloo** [comment]
Good to hear!
