### ISSUE TITLE
Can't ssh with user app

### ISSUE THREAD

**Issue by nielsdebruin** [ByteInternet/hypernode-vagrant#18]
I installed this box on both my windows pc and mac however on both can't see to ssh into the box as the 'app' user. Hypernode.local doens't work at all, using localhost port 2222 gives me invalid public key error (regular vagrant ssh does work, but that's not the app user).

**Comment by allardhoeve** [comment]
Did you try to using vagrant ssh to ssh in? If you want to log in as the
user app, please check if your SSH public key is in the authorized keys
file. If not please add it. Otherwise, load the vagrant SSH key in your
agent, that should do.

**Comment by nielsdebruin** [comment]
vagrant ssh command works. However I see only one key in the on ~/.ssh/authorized_key file (on guest). So how would I add a keys to make the app user work. 

I also added my vagrant output:

Bringing machine 'hypernode' up with 'virtualbox' provider...
==> hypernode: Importing base box 'hypernode'...
==> hypernode: Matching MAC address for NAT networking...
==> hypernode: Checking if box 'hypernode' is up to date...
==> hypernode: Setting the name of the VM: hypernode-vagrant_hypernode_1436093245788_28107
==> hypernode: Clearing any previously set network interfaces...
==> hypernode: Preparing network interfaces based on configuration...
    hypernode: Adapter 1: nat
    hypernode: Adapter 2: hostonly
==> hypernode: Forwarding ports...
    hypernode: 80 => 8080 (adapter 1)
    hypernode: 3306 => 3307 (adapter 1)
    hypernode: 22 => 2222 (adapter 1)
==> hypernode: Booting VM...
==> hypernode: Waiting for machine to boot. This may take a few minutes...
    hypernode: SSH address: 127.0.0.1:2222
    hypernode: SSH username: vagrant
    hypernode: SSH auth method: private key
    hypernode: Warning: Connection timeout. Retrying...
    hypernode: Warning: Connection timeout. Retrying...
    hypernode: Warning: Connection timeout. Retrying...
    hypernode:
    hypernode: Vagrant insecure key detected. Vagrant will automatically replace
    hypernode: this with a newly generated keypair for better security.
    hypernode:
    hypernode: Inserting generated public key within guest...
    hypernode: Removing insecure key from the guest if its present...
    hypernode: Key inserted! Disconnecting and reconnecting using new SSH key...
==> hypernode: Machine booted and ready!
GuestAdditions versions on your host (4.2.22) and guest (4.3.14) do not match.
stdin: is not a tty
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
linux-headers-3.2.0-77-generic is already the newest version.
linux-headers-3.2.0-77-generic set to manually installed.
The following packages were automatically installed and are no longer required:
  linux-headers-3.2.0-30 linux-headers-3.2.0-30-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
stdin: is not a tty
mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
Installing Virtualbox Guest Additions 4.2.22 - guest version is 4.3.14
stdin: is not a tty
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.2.22 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 4.3.14 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
You should restart your guest to make sure the new modules are actually used

Installing the Window System drivers ...fail!
(Could not find the X.Org or XFree86 Window System.)
An error occurred during installation of VirtualBox Guest Additions 4.2.22. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
stdin: is not a tty
==> hypernode: Checking for guest additions in VM...
==> hypernode: Setting hostname...
==> hypernode: Configuring and enabling network interfaces...
==> hypernode: Mounting shared folders...
    hypernode: /vagrant => /Users/niels/Development/hypernode-vagrant
    hypernode: /data/web/nginx => /Users/niels/Development/hypernode-vagrant/data/web/nginx
    hypernode: /data/web/public => /Users/niels/Development/hypernode-vagrant/data/web/public
==> hypernode: Updating /etc/hosts file on active guest machines...
==> hypernode: Updating /etc/hosts file on host machine (password may be required)...
==> hypernode: Running provisioner: shell...
    hypernode: Running: /var/folders/kx/c6slq23d79956zpz42xr50jr0000gn/T/vagrant-shell20150705-616-1ut0zi4.sh
==> hypernode: stdin: is not a tty

**Comment by allardhoeve** [comment]
Try `sudo su - app` to gain access to the app user. Then just edit the file using vim.

Or run `sudo vim /data/web/.ssh/authorized_keys` to access the file directly.

**Comment by nielsdebruin** [comment]
Thanks, I got into app user with `sudo su - app`. Added the ssh keys and found the app user mysql password.

However I do have one question regarding the hypernode.local alias. In the readme it states that you can ssh to the server using hypernode.local however I checked the vagrantfile and found that the virtualbox hostname was set to: xxxxxx-dummy-magweb-vgr.nodes.hypernode.local. The two aliases are set to example.hypernode.local and hypernode-alias, which both work (So no hypernode.local). I am not an export on vagrant at all but shouldn't there be some reference to hypernode.local ?
