### ISSUE TITLE
Port forwarding on LXC not working

### ISSUE THREAD

**Issue by pauluse** [ByteInternet/hypernode-vagrant#181]
Right now port forwarding is only applied when the box is run through the virtualbox provider.
https://github.com/ByteInternet/hypernode-vagrant/blob/master/Vagrantfile#L77

[vagrant-lxc](https://github.com/fgrehm/vagrant-lxc) allows port-forwarding through redir.

**Comment by pauluse** [comment]
Created a PR for this #182

**Comment by vdloo** [comment]
closed by https://github.com/ByteInternet/hypernode-vagrant/pull/182
