### ISSUE TITLE
Allow static IP to be assigned

### ISSUE THREAD

**Issue by pauluse** [ByteInternet/hypernode-vagrant#188]
In some cases (when running multiple instances at once) we would like to assign a static IP to the boxes. For the Virtualbox provider there is not much of an problem while setting a static IP.
```
      # Allow a static IP to be assigned if set in the settings
      if (settings.has_key?("ip") && settings["ip"] != "dhcp")
        override.vm.network "private_network", ip: settings["ip"]
      else
        override.vm.network "private_network", type: "dhcp"
      end
```

Private networking for LXC is currently experimental. Instead of assigning a static IP a new eth device will be created on the guest and host system. On LXC a bridge name needs to be provided as well:
```config.vm.network "private_network", ip: "192.168.2.100", lxc__bridge_name: 'vlxcbr1'```

Above also requires brctl (bridge-utils) to be installed on the host system. For me this isn't an issue, but I would like to hear the opinion from others whether I should create a PR for this or not.

EDIT: More information about private networking is available on [vagrant-lxc](https://github.com/fgrehm/vagrant-lxc#private-networks-experimental)

**Comment by vdloo** [comment]
closed by https://github.com/ByteInternet/hypernode-vagrant/pull/190
