### ISSUE TITLE
Mailcatcher voor email afhandeling

### ISSUE THREAD

**Issue by TimVroom** [ByteInternet/hypernode-vagrant#2]
Voor het afvangen van e-mails op de vagrant machine is het handig om [http://mailcatcher.me/](mailcatcher) te gebruiken.

Bij de provisioning kun je hiervoor: `gem install mailcatcher` gebruiken.
Voor de php configuratie (zodat hij altijd naar mailcatcher mailt) stel je hetvolgende in bij de php.ini:
`sendmail_path = /usr/bin/env catchmail`

Eventueel als opstart-script kan [https://gist.github.com/EHLOVader/9233230](https://gist.github.com/EHLOVader/9233230) gebruikt worden.

De mailomgeving kan dan via de browser via [http://ip-adres:1080](http://ip-adres:1080) benadert worden.
Mail kan tevens naar de mailer verstuurt worden (via sendmail) op adres: 127.0.0.1:1025

**Comment by allardhoeve** [comment]
Well, it wasn't tomorrow :smile:  But I got to it today. If the builds succeed, I'll push an update today.

**Comment by timneutkens** [comment]
Hey @allardhoeve,
Saw that you added mailhog 26th of februari. Maybe close this ticket 👍

**Comment by vdloo** [comment]
thanks for the reminder!
