### ISSUE TITLE
nginx configuration

### ISSUE THREAD

**Issue by razbakov** [ByteInternet/hypernode-vagrant#20]
Which file is responsible for nginx configuration?

I tried to edit this file `/etc/nginx/sites-available/default` but it seems that it is doesn't work

**Comment by vdloo** [comment]
You can configure nginx by placing configuration files in the nginx directory in your home dir: ```/data/web/nginx```. Check out [this article](http://support.hypernode.com/knowledgebase/how-to-use-nginx/) in the Hypernode knowledgebase for specifics.
