### ISSUE TITLE
vagrant up keeps installing vagrant-hypconfigmgmt

### ISSUE THREAD

**Issue by Darkbelg** [ByteInternet/hypernode-vagrant#203]
I updated vagrant and virtualbox to the latest version and now vagrant-hypconfigmgmt keeps installing.

It seems similar to this stackoverflow answer https://stackoverflow.com/questions/19492738/demand-a-vagrant-plugin-within-the-vagrantfile#answer-28801317

**Comment by vdloo** [comment]
Hi @Darkbelg, on what operation does it happen? vagrant up? vagrant box update? more information would be helpful. what platform are you running on? Linux? Any problem is probably in this codeblock: https://github.com/ByteInternet/hypernode-vagrant/blob/master/Vagrantfile#L11 perhaps you can poke around a bit in there

**Comment by Darkbelg** [comment]
The system is linux ubuntu 18.04 it happens on any vagrant up command. I can now also reproduce it on windows 10.

I will take a look if i can do a temporary fix.

**Comment by Darkbelg** [comment]
When i do 
puts !Vagrant.has_plugin?("vagrant-hypconfigmgmt", version = VAGRANT_HYPCONFIGMGMT_VERSION)

It keeps returning true not sure why.

**Comment by Darkbelg** [comment]
At the moment i'm getting around this by running it once and then putting the code in comments.

Can you just tell me if you are able to reproduce the issue or is it just something on my end ?

**Comment by vdloo** [comment]
yeah I can reproduce this now, I'll investigate:
```
[vdloo@arrakis hypernode-vagrant]$ vagrant up
Installing the 'vagrant-hypconfigmgmt --version '0.0.11'' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hypconfigmgmt (0.0.11)'!
Installed the vagrant-hypconfigmgmt plugin.
For the next configuration step, please again run: "vagrant up"
[vdloo@arrakis hypernode-vagrant]$ vagrant up
Installing the 'vagrant-hypconfigmgmt --version '0.0.11'' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hypconfigmgmt (0.0.11)'!
Installed the vagrant-hypconfigmgmt plugin.
For the next configuration step, please again run: "vagrant up"
```

**Comment by vdloo** [comment]
@Darkbelg it seems like this changed in newer versions of Vagrant. If you don't want to deal with this problem you could downgrade (2.0.* seems to still work). Alternatively I would like to suggest this change: https://github.com/ByteInternet/hypernode-vagrant/pull/204 that would remove the automatic installation from the Vagrantfile. Then people would just have to run `vagrant plugin install vagrant-hypconfigmgmt` themselves according to the README. Note that there are more looming issues with this Vagrant box though. The boxfile we use currently is not compatible with [LXC 3.0](https://linuxcontainers.org/lxc/news/) which will eventually also make it to the major distros and I'm not sure we plan on supporting that (if you use VirtualBox this specific example isn't very relevant though). Depending on your purposes you could also consider using the more recent [hypernode-docker](https://github.com/ByteInternet/hypernode-docker).

**Comment by Darkbelg** [comment]
@vdloo i tried downgrading vagrant but i ran into other errors. I have never actually got LXC to work on my linux machine. so i'm going to stop trying it. Is Docker better for magento 2 development on linux ?

**Comment by vdloo** [comment]
> i tried downgrading vagrant but i ran into other errors.

I'm currently getting other errors on my Archlinux machine as well that I did not get before.

```
[vdloo@arrakis hypernode-vagrant]$ export VAGRANT_DEFAULT_PROVIDER=virtualbox
[vdloo@arrakis hypernode-vagrant]$ vagrant status
/home/vdloo/code/projects/hypernode-vagrant/Vagrantfile:7: warning: already initialized constant VAGRANTFILE_API_VERSION
/home/vdloo/code/projects/hypernode-vagrant/Vagrantfile:7: warning: previous definition of VAGRANTFILE_API_VERSION was here
/home/vdloo/code/projects/hypernode-vagrant/Vagrantfile:8: warning: already initialized constant VAGRANT_HYPCONFIGMGMT_VERSION
/home/vdloo/code/projects/hypernode-vagrant/Vagrantfile:8: warning: previous definition of VAGRANT_HYPCONFIGMGMT_VERSION was here
/home/vdloo/code/projects/hypernode-vagrant/Vagrantfile:11: warning: already initialized constant SETTINGS_FILE
/home/vdloo/code/projects/hypernode-vagrant/Vagrantfile:11: warning: previous definition of SETTINGS_FILE was here
The provider 'lxc' could not be found, but was requested to
back the machine 'hypernode'. Please use a provider that exists.

Vagrant knows about the following providers: docker, hyperv, virtualbox
```

Looks like there are more incompatibilities in the newer versions of things and unfortunately I don't have the time right now to go dive into that.

> Is Docker better for magento 2 development on linux ?

That really depends on your use-case. It has many advantages and disadvantages. For example, the Docker has no init system (no systemd / no concept of services etc) so it would not be 'exactly' like a real Hypernode and it depends on what type of things you need to test whether that is relevant or not. The hypernode-docker does use our Ubuntu repository for the packages it contains so the big advantage of using that (or hypernode-vagrant) is that you'll be testing against exactly the same software versions as that would be running on a real Hypernode.

There are some other related projects that I hear good things about that achieve the same thing as hypernode-vagrant but might work better for you in the environment you are trying to run things on (but they will not be as close to Hypernode as these two projects, again it depends on what you're doing whether or not that is important).

I hear valet-plus by @timneutkens is great: https://github.com/weprovide/valet-plus It runs things locally on your host so there's no complication in terms of VM or container abstraction. It is mac specific though. Alternatively there is this docker-compose configuration by @JeroenBoersma which I also hear is nice https://github.com/JeroenBoersma/docker-compose-development. And Magento also has an official dev box: https://github.com/magento/magento2devbox-web (but I'm not sure if that's still under active development).

Or you could also just get a hosted dev Hypernode and then you don't have to configure anything on your computer which might be the least time consuming way to do things if you just want to do some testing in a 'real hypernode' environment.
