### ISSUE TITLE
magerun2 outdated in precise

### ISSUE THREAD

**Issue by Darkbelg** [ByteInternet/hypernode-vagrant#205]
Can magerun2 be updated in the precise boxes from 1.5.0 to the latest version or drop it from vagrant config ?

**Comment by Darkbelg** [comment]
local.yml
`---
fs:
  folders:
    magento2:
      host: data/web/magento2
      guest: "/data/web/magento2"
    nginx:
      host: data/web/nginx/
      guest: "/data/web/nginx/"
    composer:
      host: "/_ABSOLUTE_PATH_TO_HOME_DIR_/.composer/"
      guest: "/data/web/.composer/"
  type: nfs
  disabled_folders:
    magento1:
      host: data/web/public
      guest: "/data/web/public"
hostmanager:
  extra-aliases:
  - newparislondres.test
  - www.newparislondres.test
  default_domain: newparislondres.hypernode.local
magento:
  version: 2
php:
  version: 7.0
varnish:
  state: false
firewall:
  state: false
cgroup:
  state: false
xdebug:
  state: true
vagrant:
  box: hypernode_php7
  box_url: http://vagrant.hypernode.com/customer/php7/catalog.json
ubuntu_version: precise`

**Comment by vdloo** [comment]
Hi @Darkbelg we removed the infrastructure to update the Precise base box in 2016, so we can not update the box. But you can upgrade magerun yourself in a Vagrant provisioning hook by running `/usr/local/bin/magerun self-update` as root. Have you tried the Xenial box yet?

**Comment by Darkbelg** [comment]
@vdloo Ah ok i didn't know that was the situation. Somebody at my company still used it. And i was wondering what the reason was for this.
