### ISSUE TITLE
phpMyAdmin not working

### ISSUE THREAD

**Issue by rikwillems** [ByteInternet/hypernode-vagrant#22]
In my clean setup I can't get phpMyAdmin to work. When I open hypernode.local/phpmyadmin it fails, also after editing the config to remove the 404 as per issue #6. Also when I try http://localhost:8080/phpmyadmin it redirects to http://localhost/, being my host machine.

**Comment by vdloo** [comment]
Today we released box version ```v2647``` which addresses this. If you run ```vagrant box update``` you should get the new version. Remember to [back up your db](https://github.com/ByteInternet/hypernode-vagrant#keeping-up-to-date-with-hypernode-versions) before upgrading though. 

phpMyAdmin can now be accessed on ```http://yourtestshopname.hypernode.local/phpmyadmin```.

Take a look [here ](https://github.com/ByteInternet/hypernode-vagrant#running-multiple-hypernode-vagrant-boxes-at-the-same-time) for more information about how to configure the box name.
