### ISSUE TITLE
Update to PHP 5.5?

### ISSUE THREAD

**Issue by hslatman** [ByteInternet/hypernode-vagrant#26]
Will the box eventually be updated to run PHP 5.5+?

**Comment by hslatman** [comment]
Ok, cool. I was looking into running Magento 2 on this, but that failed early ;-). I will figure try to figure something out in the meantime.

**Comment by vdloo** [comment]
We released a new version of the box earlier this week, php5.5 is now installed.
```
app@a199d9-mytestnode-magweb-vgr:~$ php --version
PHP 5.5.30-1+deb.sury.org~precise+1 (cli) (built: Oct  4 2015 16:14:34) 
```

**Comment by mariarti** [comment]
@hslatman 
Magento2 require php5.6, not 5.5

**Comment by hslatman** [comment]
@mariarti 
Thanks, but 5.5 **is** supported. http://devdocs.magento.com/guides/v2.0/install-gde/bk-install-guide.html.

**Comment by IvanChepurnyi** [comment]
The PHP5.6 is a minimum required version for 2.1 Magento version
http://devdocs.magento.com/guides/v2.1/install-gde/prereq/prereq-overview.html

**Comment by IvanChepurnyi** [comment]
Any plan on fixing this problem? As for now I cannot install on PHP5.6 Magneto 2.1.

**Comment by vdloo** [comment]
Hi @IvanChepurnyi, we are not planning to add 5.6 to the Hypernode stack at this point in time. If you are running Magento 2 we recommend that you use PHP 7. If there are plugins that do not support PHP7 (but do support PHP 5.6) that is unfortunate but currently we have no plans to start supporting 5.6 additionally to 5.5.
