### ISSUE TITLE
can't 'vagrant up' -  No usable default provider could be found for your system

### ISSUE THREAD

**Issue by mariarti** [ByteInternet/hypernode-vagrant#29]
VirtualBox Version 5.0.14 r105127
vagrant version 1.7.2
CentOS release 6.7 (Final) x64

'$ vagrant plugin install vagrant-vbguest vagrant-hostmanager
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vbguest (0.11.0)'!
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.8.0)'!
$ vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

$ vagrant up --provider=VirtualBox
The provider 'VirtualBox' could not be found, but was requested to
back the machine 'hypernode'. Please use a provider that exists.

'

**Comment by vdloo** [comment]
Hi @mariarti, try 
```
vagrant up --provider virtualbox
```

**Comment by mariarti** [comment]
no luck with 'vagrant up --provider virtualbox'
only update to Vagrant 1.8.1 fix issue.

Thanks for answer.
