### ISSUE TITLE
502 bad gateway via 127.0.0.1:8080

### ISSUE THREAD

**Issue by mariarti** [ByteInternet/hypernode-vagrant#33]
Have hypernode updated from version '2638' to '2647'
VirtualBox Version 5.0.14 r105127
vagrant version 1.8.1
CentOS release 6.7 (Final) x64

Issue: got 502 bad gateway via 127.0.0.1:8080
as I can understand accessing via port 8080 I go to port 80 in VM, so I fall to outside.conf, right?
there I see that all requests go to 127.0.0.1:6081 i.e. varnish , but in 'ps ax|grep varnish' i don't see varnish runnig and nothing in '/var/log/varnish' folder.

I expect to see default hypernode index page from folder /data/web/public

/var/log/nginx/access.log
```
{"time":"2016-02-15T21:19:11+00:00", "remote_addr":"10.0.2.2", "remote_user":"-", "host":"127.0.0.1:8080", "request":"GET / HTTP/1.1", "status":"502", "body_byt
es_sent":"568", "referer":"-", "user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36", "reques
t_time":"0.000", "handler":"varnish", "country":"-", "android_dupe_bug":"", "ssl_cipher":"-", "ssl_protocol":"-"}
{"time":"2016-02-15T21:19:11+00:00", "remote_addr":"10.0.2.2", "remote_user":"-", "host":"127.0.0.1:8080", "request":"GET /favicon.ico HTTP/1.1", "status":"502"
, "body_bytes_sent":"568", "referer":"http://127.0.0.1:8080/", "user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.
2564.109 Safari/537.36", "request_time":"0.000", "handler":"varnish", "country":"-", "android_dupe_bug":"", "ssl_cipher":"-", "ssl_protocol":"-"}
{"time":"2016-02-15T21:19:12+00:00", "remote_addr":"10.0.2.2", "remote_user":"-", "host":"127.0.0.1:8080", "request":"GET / HTTP/1.1", "status":"502", "body_byt
es_sent":"568", "referer":"-", "user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36", "reques
t_time":"0.000", "handler":"varnish", "country":"-", "android_dupe_bug":"", "ssl_cipher":"-", "ssl_protocol":"-"}
{"time":"2016-02-15T21:19:12+00:00", "remote_addr":"10.0.2.2", "remote_user":"-", "host":"127.0.0.1:8080", "request":"GET /favicon.ico HTTP/1.1", "status":"502"
, "body_bytes_sent":"568", "referer":"http://127.0.0.1:8080/", "user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.
2564.109 Safari/537.36", "request_time":"0.000", "handler":"varnish", "country":"-", "android_dupe_bug":"", "ssl_cipher":"-", "ssl_protocol":"-"}
```

And what is the strange ip 10.0.2.2? I don't have this ip anywere.

**Comment by vdloo** [comment]
Hi Mariarti,

The 10.0.2.2 is from the [private address space](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces) that is used by Vagrant for [networking](https://www.vagrantup.com/docs/networking/private_network.html).

You can see that one of your interfaces is bound to this subnet
```
root@beb7b8-projects-magweb-vgr /home/vagrant # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:88:0c:a6 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:52:3c:69 brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.3/24 brd 172.28.128.255 scope global eth1
```

Did you try accessing the web page with one of the host [aliases](https://github.com/byteinternet/hypernode-vagrant#running-multiple-hypernode-vagrant-boxes-at-the-same-time)? Try ```http://hypernode.local```

**Comment by mariarti** [comment]
Yes, i do - no luck. (timeout error) I think it's due to /etc/hosts - records with that aliases points to old VM '2638' 
' ## vagrant-hostmanager-start id: 511dbfe6-b8fd-4591-a05e-0181ebc75469
192.168.33.100  xxxxxx-dummy-magweb-vgr.nodes.hypernode.local
192.168.33.100  example.hypernode.local
192.168.33.100  hypernode-alias
## vagrant-hostmanager-end'
and suddenly i remember that update can broke whole settings, so i delete all vagrant VM and ~/.vagrant.d folder as well. Then i try to install all from scratch, begining from git clone:
http://pastebin.com/VACfdxgY
Same result, but another error - 403 (but i am not surprised, because installation was not finished correctly )

**Comment by vdloo** [comment]
This indicates that updating the box went wrong
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hypernode' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'http://vagrant.hypernode.com/catalog.json'
    default: URL: http://vagrant.hypernode.com/catalog.json
==> default: Adding box 'hypernode' (v2647) for provider: virtualbox
    default: Downloading: http://vagrant.hypernode.com/hypernode.vagrant.release-2647.box
An error occurred while downloading the remote file. The error message, if any, is reproduced below. Please fix this error and try again.
 
transfer closed with 825212425 bytes remaining to read
```
you could try ```$  vagrant box update``` again to get the latest box before you ```$ vagrant up``` again.

Did mounting the synced folders work before on your system? 

Also, you should remove all entries in your /etc/hosts that refer to 192.168.33.100 because the current master of this repository no longer uses static IPs. If you want to be sure to have a fresh install you can remove all entries in /etc/hosts in the ```vagrant-hostmanager-start``` and ```vagrant-hostmanager-end``` blocks. Hope that helps!

**Comment by mariarti** [comment]
1) As i mentioned previously: I completely delete ALL files related to old VM 2638. 
You point that *updating the box* , but this was not updating - it was installing new box 2647.
Yes, there is exist another non critical issue - that every time when vagrant try download hypernode.vagrant.release-2647.box it disconnected from http://vagrant.hypernode.com/ unexpectedly 3-4 times (not only for me this issue exist), so i repeat 'vagrunt up' and downloading continue to work till install process. But this is not a root of issue. And at this point nothing to updtae - hypernode.vagrant.release-2647.box already updated and last version.
2) Yes, on old VM '2638' all folders mountings works well, no probllem.
3) Ok, I clean  that records from /etc/hosts, but for now it is early to try get access via hostnames (due to unfinished installation)

So, new VM 2647, installed from scratch does not work as previous  old VM '2638'.

**Comment by vdloo** [comment]
1. Yes, you are right I misread. Your pastebin log shows that the box was successfully downloaded after retrying ```vagrant up```. I added the issue to the [troubleshooting section](https://github.com/ByteInternet/hypernode-vagrant#transfer-closed-with-x-bytes-remaining-to-read) of the README for if people run into the same problem. Retrying it once or twice has been enough in the cases that I've encountered though, I can imagine that needing 4 attempts is bothersome. Is there another internet connection that you can use to test from? I'm not sure what's causing that issue. 

2. We haven't changed anything relating to the synced folders since that release. You could try overwriting the box version to the old version in the Vagrantfile
```
config.vm.box = "hypernode"
config.vm.box_url = "http://vagrant.hypernode.com/catalog.json"
config.vm.box_version = "2638"
```
and see if that still works as expected.

**Comment by mariarti** [comment]
1) From troubleshooting section about trying again: it is not correct advice 'vagrant box update' if someone try install first time, error will appear:
'$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hypernode' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 2638
==> default: Loading metadata for box 'http://vagrant.hypernode.com/catalog.json'
    default: URL: http://vagrant.hypernode.com/catalog.json
==> default: Adding box 'hypernode' (v2638) for provider: virtualbox
    default: Downloading: http://vagrant.hypernode.com/hypernode.vagrant.release-2638.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

transfer closed with 1162935461 bytes remaining to read
$ vagrant box update
==> default: Box 'hypernode' not installed, can't check for updates.'
Another internet connection does not help, in another location - same issue. 

2) I do not want to upgrade/downgrade due to misconfiguration between box versions (your coment higher: "Also, you should remove all entries in your /etc/hosts that refer to 192.168.33.100 because the current master of this repository no longer uses static IPs." )

So, i add 'config.vm.box_version = "2638"' to Vagrantfile and try to install once more from scratch.

**Comment by vdloo** [comment]
You are correct, I was under the impression that you could run ```vagrant update``` after a failed ```vagrant up``` because it prints ```==> hypernode: Adding box 'hypernode' (v2653) for provider: virtualbox``` but that is not the case. I'll update the documentation, thanks.

Did you manage to get 2638 running as before with the pinned box_version? Or do you still get the ```/sbin/mount.vboxsf: mounting failed with the error: No such device``` error? If that's the case, is there something you changed about your setup since it last worked? Did you perhaps upgrade virtualbox or vagrant?

**Comment by mariarti** [comment]
and same issue
'default: /vagrant => /backup/hypernode-vagrant
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

stdin: is not a tty
/sbin/mount.vboxsf: mounting failed with the error: No such device
'
May be root of this issue is different versions guest additions:
'==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 5.0
'
because when i install 2638 first time I use vagrant 1.7.2 (in that case  vagrant was miss provider ), and after this fail i update vagrant to latest 1.8.1. And every time when 'vagrant up' with correct installed 2638 becomes up it show message that guest addition are different and *start compiling new one for my VM 5.x* and only after this operation it starts to try mount shared folders (with succes).

**Comment by vdloo** [comment]
I upgraded my Virtualbox to ```Version 5.0.14 r105127``` and now I get the same error
```
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/vdloo/code/projects/hypernode-vagrant
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

stdin: is not a tty
/sbin/mount.vboxsf: mounting failed with the error: No such device
```

Seems like this vagrant box isn't compatible with VirtualBox 5.0 for now unfortunately. On 4.* it automatically builds the virtualbox guest additions kernel modules.

About the connection errors, we might have found what is causing those closed transfers. Can you verify if when that happens there is at least 5 seconds no traffic being received? You can use something like nload.

**Comment by mariarti** [comment]
About connection error: it works better (longer period before connect lost), but still exist
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hypernode' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'http://vagrant.hypernode.com/catalog.json'
    default: URL: http://vagrant.hypernode.com/catalog.json
==> default: Adding box 'hypernode' (v2653) for provider: virtualbox
    default: Downloading: http://vagrant.hypernode.com/hypernode.vagrant.release-2653.box
    default: Progress: 1% (Rate: 731k/s, Estimated time remaining: 0:29:14)
    default: Progress: 29% (Rate: 623k/s, Estimated time remaining: 0:21:55)
    default: Progress: 50% (Rate: 402k/s, Estimated time remaining: 0:15:21)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

transfer closed with 621455248 bytes remaining to read
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hypernode' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'http://vagrant.hypernode.com/catalog.json'
    default: URL: http://vagrant.hypernode.com/catalog.json
==> default: Adding box 'hypernode' (v2653) for provider: virtualbox
    default: Downloading: http://vagrant.hypernode.com/hypernode.vagrant.release-2653.box
==> default: Box download is resuming from prior download progress
    default: Progress: 20% (Rate: 642k/s, Estimated time remaining: 0:11:50)

```

**Comment by genisd** [comment]
We found a possible cause for the download interrupts. We're investigating a proper solution and may try a candidate workaround soon!

**Comment by genisd** [comment]
The box download issues should be resolved now. Please let us know how it goes!

**Comment by vdloo** [comment]
@mariarti can you confirm that you have vagrant-vbguest installed? A colleague mentioned that he got it running with the latest vagrant and virtualbox. I noticed that I didn't have the vagrant-vbguest installed and after I did I had no problems mounting the synced folders.

**Comment by mariarti** [comment]
@genisd thanks, good job. latest vb downloaded without interrupts.
@vdloo good news:
Yes, I can confirm, that installing `vagrant plugin install vagrant-vbguest` fix issue with mounting sharing folders (I have not installed vagrant-vbguest before ). http://pastebin.com/Cyu8F1a3
 bad news:
after mounted folders 
```
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20160217-22311-55p257.sh
==> default: stdin: is not a tty
```

**Comment by vdloo** [comment]
Hi @mariarti,

Great, looks like everything works! The ```stdin: is not a tty``` message is harmless, see https://github.com/ByteInternet/hypernode-vagrant#-default-stdin-is-not-a-tty

**Comment by mariarti** [comment]
@vdloo Thanks a lot for your patience 
(and my too, may be your company hire me as tester ))) )

Now I can access 127.0.0.1:8080 and see index page in hypernode style.
But I can't access to the same page via hostname nor other variants and combinations (no records in /etc/hosts - so it can't resolve localhost ip, i think), if I remember right - adding ip/names  to /etc/hosts went directly after (or during) provisioning.

**Comment by vdloo** [comment]
@mariarti perhaps you also wiped the hostmanager plugin when starting from scratch?

 ```vagrant plugin install vagrant-hostmanager```

**Comment by mariarti** [comment]
Hmm, you are right. vagrant-hostmanager was absent. I install it and get such rows:
```
==> hypernode: Checking for guest additions in VM...
==> hypernode: Setting hostname...
==> hypernode: Configuring and enabling network interfaces...
==> hypernode: Mounting shared folders...
    hypernode: /vagrant => /backup/hypernode-vagrant
    hypernode: /data/web/nginx => /backup/hypernode-vagrant/data/web/nginx
    hypernode: /data/web/public => /backup/hypernode-vagrant/data/web/public
==> hypernode: Updating /etc/hosts file on active guest machines...
```
So, vagrant wrote that he update` /etc/hosts` , but in fact - not (no records for hypernode.local), and request via hypernode.local still does not work.

I am guess that script should check required plugins/modules. Because before wipe they exist for sure, and I think they was installed previously by magento EE demo (original pack for learning).

May be more plugins should be added for right work?
