### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by mhobbink** [ByteInternet/hypernode-vagrant#44]
Trying to install magento 1.9.2.3 via composer on vagrant 1.8.1 and provider VirtualBox 5.0.14 (OS X). Performance of the hypernode-box is very poor; slow and lot's of 504-gateway-timeouts.

I didn't experience these problems with older hypernode-vagrants. 

Any solution for the 504's?

**Comment by genisd** [comment]
Can you advise which vagrant release you have now and which one before?
That way we know the precise list of differences between the version were running and the one you are running now.

**Comment by mhobbink** [comment]
Currently running latest box (2684). Boxes were running fine until week or 2 ago. Don't know what release

**Comment by genisd** [comment]
```vagrant box list``` should show the previous box version that you had downloaded.

```127.0.0.1:6081``` is varnish, which we included recently into the vagrant image.
If you login as root (```vagrant ssh hypernode``` and then ```sudo -s```), is varnish currently running for you? You could check with ```netstat -ntlp``` if varnish is listening on port 6081.

You may need to start varnish and place a default vcl under ```/data/var/varnish/default.vcl``` containting the following:

```
vcl 4.0;
backend default {
    .host = "127.0.0.1";
    .port = "8080";
}
```

We would expect this default vcl to be present already, but maybe something goes wrong in the update path? In particular this varnish is now version 4, the default version 3 vcl (without the vcl 4.0; header) will not load, so mabye your varnish instance never came up?

**Comment by mhobbink** [comment]
vagrant box list
hypernode                       (virtualbox, 2659)
hypernode                       (virtualbox, 2677)
hypernode                       (virtualbox, 2684)
But I recently reinstalled OSX so not all versions that I used are listed. Hypernode-vagrant on this install where performing bad.

Just followed the steps above. 
- Varnish-deamon was listening on 6081. 
- Copied vcl-config to default.vcl
- Restarted varnish.
No 504's so far and improved performance :)

**Comment by allardhoeve** [comment]
Did you solve the issue? I'd like to add it to the FAQ if it is something
others might encounter.

**Comment by mhobbink** [comment]
I followed the steps that were mentioned and that solved it for me.
Haven’t experienced any time-outs anymore.



Op 26 feb. 2016, om 17:34 heeft Allard Hoeve <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Did you solve the issue? I'd like to add it to the FAQ if it is something
others might encounter.
