### ISSUE TITLE
unable te create symbolic link to public

### ISSUE THREAD

**Issue by Frits1980** [ByteInternet/hypernode-vagrant#57]
Due to the lack of shutting down Nginx it's not possible to make the public links in /public/ explained in 
https://support.hypernode.com/knowledgebase/installing-magento-2-on-hypernode/ in step 6.
So it's not working.

But maybe it's just me. I'm a simple front-end dev who likes to create a magento2 shop, but for some reason it's not possible to do so without extensive Linux knowledge. Which I find odd in a century where everything is subjected to UX design. Why isn't there a company which makes a click and serve dev/stage/production process possible?

**Comment by vdloo** [comment]
Hi,

I just tried creating links in the synced /data/web/public directory and it seemed to work.

```
app@250730-projects-magweb-vgr:~$ mkdir magento2/pub -p 
app@250730-projects-magweb-vgr:~$ cd magento2/pub/
app@250730-projects-magweb-vgr:~/magento2/pub$ ls
app@250730-projects-magweb-vgr:~/magento2/pub$ touch file1.txt file2.txt file3.txt
app@250730-projects-magweb-vgr:~/magento2/pub$ cd 
app@250730-projects-magweb-vgr:~$ ls
incidents  magento2  nginx  public  staging
app@250730-projects-magweb-vgr:~$ cd magento2/
app@250730-projects-magweb-vgr:~/magento2$ ln -fs ../magento2/pub/* ../public/
```

Are you on windows by any chance? Can you try again with the synced dir unmounted?

```
vagrant ssh
sudo su
umount /data/web/public 
```

How would you feel about a box version with magento1 or magento2 pre-installed?

**Comment by Frits1980** [comment]
Thank you for the quick response. I removed the mount and tried again and it worked.

Of course my next problem arises... I can't reach magento through my browser. This is why I so desperately would want a sollution what just works. My experience with Linux is that it is always working from 1 problem to the next. I don't know what you are proposing with a "box" with magento. I've tried bitnami local thingy that works pretty well, but I'm missing a dev/stage/production environment. And a GUI for backup/rollback and deployment to next environment. But maybe I'm just to demanding, I don't know.

**Comment by vdloo** [comment]
Alright, keep in mind that the data in the public directory will not persist outside of the Vagrant box without the mount though, so if you want to keep your data after a vagrant destroy make sure to back it up. 

What does your hosts file look like? Do hits show up in the logs? ```tail -f /var/log/nginx/*```

**Comment by Frits1980** [comment]
My hosts file says this: ```
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.0.2.15 b0d8bb-info-magweb-vgr.nodes.hypernode.local b0d8bb-info-magweb-vgr
127.0.0.1 mysqlmaster mysqlmaster.dummytag.hypernode.io
127.0.0.1 redismaster redismaster.dummytag.hypernode.io
127.0.0.1 worker worker.dummytag.hypernode.io
127.0.0.1 varnish varnish.dummytag.hypernode.io

## vagrant-hostmanager-start
10.0.2.15       b0d8bb-info-magweb-vgr.nodes.hypernode.local
10.0.2.15       hypernode.local
10.0.2.15       hypernode-alias
10.0.2.15       info.hypernode.local
10.0.2.15       b0d8bb.hypernode.local
## vagrant-hostmanager-end
```
Tail does not show anything when I hit refresh in my browser. My windows IP is 192.168.38.150. My Vagrant box has 10.0.2.15. I can't ping it from windows. Maybe it has something to do with VirtualBox network settings? I don't know.

**Comment by vdloo** [comment]
I think you might be running into [this](https://github.com/ByteInternet/hypernode-vagrant/pull/55). Can you update your repository to the latest revision and re-create the box?

```
git pull origin master
vagrant destroy -f  # mind to copy all data you want to keep of the box first
vagrant up 
```

Otherwise if you don't want to destroy your box you could fix it manually by logging in to the Vagrant box and getting the IP of the eth1 interface.

```
vagrant@250730-projects-magweb-vgr:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:88:0c:a6 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:99:f1:4b brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.3/24 brd 172.28.128.255 scope global eth1
```

Now put the address of the eth1 interface (in my case 172.28.128.3) in the /etc/hosts file on the host (not in the Vagrant box) in the place of the 10.0.2.15 address.

```
# /etc/hosts
## vagrant-hostmanager-start
172.28.128.3       b0d8bb-info-magweb-vgr.nodes.hypernode.local
172.28.128.3       hypernode.local
172.28.128.3       hypernode-alias
172.28.128.3       info.hypernode.local
172.28.128.3       b0d8bb.hypernode.local
## vagrant-hostmanager-end
```

**Comment by Frits1980** [comment]
Ok, I finally got it working. The change in the hosts file did it. Thank you.

I still have some questions though. How can I make sure the changes stay when I shut down the VM? If I run vagrant up it will overwrite the hosts file again with the wrong IP.

**Comment by vdloo** [comment]
If you pulled the latest master the next time you run vagrant up it should get the right IP automatically.

**Comment by hongaar** [comment]
If you're on Windows you could try to add the following line to the Vagrantfile to enable creating symlinks inside a VirtualBox guest:

```diff
config.vm.provider :virtualbox do |vbox, override|
    override.vm.network "private_network", type: "dhcp"
    override.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    override.vm.network "forwarded_port", guest: 3306, host: 3307, auto_correct: true
    vbox.memory = 2048
+    vbox.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
```

_Note_ don't add the `+`.
