### ISSUE TITLE
PHPMyAdmin geeft 404

### ISSUE THREAD

**Issue by pascaladriaansen** [ByteInternet/hypernode-vagrant#6]
Als ik naar http://hypernode.local/phpmyadmin ga krijg ik een ERROR 404. 

In /etc/nginx/conf.d/magweb.conf wordt voor PHPMyAdmin namelijk nog steeds gecheckt of de HTTP HOST *.hypernode.io is.

**Comment by vdloo** [comment]
This is in the latest box version, see https://github.com/ByteInternet/hypernode-vagrant/issues/22#issuecomment-183390302
