### ISSUE TITLE
Can't get mailhog working.

### ISSUE THREAD

**Issue by Frits1980** [ByteInternet/hypernode-vagrant#62]
Mailhog does nothing I think. When I do "ps -A |grep mail" I get nothing.
Also when I do "http://my hostname:8025/ nothing shows.
How can I get this working?

**Comment by vdloo** [comment]
Hi @frits1980, this is the ps output I'm getting on a fresh Vagrant box
```
app@5a4d48-tmp-magweb-vgr:~$ ps -A | grep mail
  960 ?        00:00:00 mailhog
```

and I can open the mailhog web interface on the host machine
```
λ /tmp/hypernode-vagrant curl -s tmp.hypernode.local:8025 | grep MailHog | head -n 1
    <title>MailHog</title>
```

What version of the box are you running? I'm running 2941. You can try updating with ```vagrant box update``` and boot a new one after destroying the current one. Also are you running php 5.5 or 7? I tested with 5.5

**Comment by Frits1980** [comment]
Ah. My fault. Was still running on 2811 php5. Updated now. Mailhog is running now. Thank you for helping.
