### ISSUE TITLE
Hostname after installation

### ISSUE THREAD

**Issue by timneutkens** [ByteInternet/hypernode-vagrant#69]
Tiny bug I experienced last saturday during the mm hackaton. Once you vagrant up the first time you get an echo from this line of code:
https://github.com/ByteInternet/hypernode-vagrant/blob/master/vagrant/provisioning/hypernode.sh#L37
What happens when you have a `-` is that it echoes everything before the first `-`. In my case `fiddle.hypernode.local` but as you can see it should be `fiddle-projects.hypernode.local`.
The hostfile etc are managed correctly.

![screenshot](https://cloud.githubusercontent.com/assets/6324199/15348759/9188032a-1ccd-11e6-845a-718f126d60c6.png)

I will try to fix this later today. This is just for reference.

**Comment by vdloo** [comment]
I think it might be better to filter '-' characters from the hypernode name in the Vagrantfile because real hypernodes also can't have names with special characters in them

**Comment by timneutkens** [comment]
Ah didn't know they weren't allowed. Then it's best to filter them out indeed. Want me to create a pull request or will you add it yourself ;)?

**Comment by vdloo** [comment]
@timneutkens sure go ahead

**Comment by timneutkens** [comment]
Since #79 was merged this can be closed now 👍
