### ISSUE TITLE
n98-magerun addon to fill Vagrantfile with parameters

### ISSUE THREAD

**Issue by peterjaap** [ByteInternet/hypernode-vagrant#9]
Maybe its an idea to create a magerun addon that takes the default Vagrantfile in your installation and asks for certain parameters interactively and places them in the Vagrantfile?

Such as; hostname, IP address, local folder to bind to /data/web/public?

**Comment by vdloo** [comment]
@peterjaap we prompt for parameters now with a bundled [vagrant plugin](https://github.com/ByteInternet/hypernode-vagrant/tree/master/vagrant/plugins/vagrant-hypconfigmgmt).

Looks like:
![prompt](https://cloud.githubusercontent.com/assets/1437341/16519910/9e78c678-3f8c-11e6-83f6-758663362421.png)

**Comment by peterjaap** [comment]
Awesome.
