### ISSUE TITLE
Sphinx Index Problem

### ISSUE THREAD

**Issue by tomlankhorst** [ByteInternet/hypernode-vagrant#93]
The Sphinx deamon returns an error when reindexing. Seems that a non existent field is being referred to.

`ERROR: index 'mage_catalog_product': sql_query_pre[1]: Unknown column 'updated' in 'field list' (DSN=mysql://uxxxxxxx_root:***@mysqlmaster:3306/dbxxxxxxx_webshop). total 0 docs, 0 bytes total 0.032 sec, 0 bytes/sec, 0.00 docs/sec total 0 reads, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg total 0 writes, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg
`
Anyone experience with this?

**Comment by vdloo** [comment]
I haven't seen this one before. Are you using Sphinx Search Ultimate by Mirasvit? Is there different behavior on a real Hypernode? afaik we do nothing different for Sphinx in the Vagrant build playbooks compared to production Hypernodes. 

Did you import the shop using the hypernode-importer by any chance? We filter some things from the db dump for import speed so maybe something too much got left out. Do your production db and the db in the vagrant look the same?

**Comment by tomlankhorst** [comment]
No difference. After some research it seemed that the Sphinx Search
Ultimate module hooks into the indexing function. It alters the index
table. So the product index had to be rebuild.

This is not an actual Hypernode issue but might be interesting for other
users.

**Comment by tomlankhorst** [comment]
Issue can be closed...
